repository_dir: triton_models
model_name: pneumonia_detection
model_version: 1

backend: onnx
onnx_source: artifacts/model.onnx
engine_source: artifacts/model.engine

max_batch_size: 8

input:
  name: input
  channels: 1
  height: 150
  width: 150

output:
  name: output
  dims: 1

instance_group:
  kind: cpu
  count: 1

dynamic_batching:
  enabled: true
  max_queue_delay_microseconds: 1000

labels:
  - NORMAL
  - PNEUMONIA

docker_image: nvcr.io/nvidia/tritonserver:23.10-py3
use_gpu: false
